language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
script:
  - python -m pytest
  - flake8 --max-complexity=6 --exclude node_modules
